/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsOnRouteImport } from './routes/whats-on'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as OpenNowRouteImport } from './routes/open-now'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as TaxonomyRouteImport } from './routes/$taxonomy'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SeriesSeriesRouteImport } from './routes/series.$series'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as FeedEventsDotrssRouteImport } from './routes/feed.events[.]rss'
import { Route as FeedArticlesDotrssRouteImport } from './routes/feed.articles[.]rss'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CSectionRouteImport } from './routes/c.$section'
import { Route as AuthorsAuthorRouteImport } from './routes/authors.$author'
import { Route as AreasAreaRouteImport } from './routes/areas.$area'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'
import { Route as AdminRedirectsRouteImport } from './routes/admin.redirects'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as TaxonomySlugRouteImport } from './routes/$taxonomy.$slug'
import { Route as CSectionSubRouteImport } from './routes/c.$section.$sub'

const WhatsOnRoute = WhatsOnRouteImport.update({
  id: '/whats-on',
  path: '/whats-on',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenNowRoute = OpenNowRouteImport.update({
  id: '/open-now',
  path: '/open-now',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomyRoute = TaxonomyRouteImport.update({
  id: '/$taxonomy',
  path: '/$taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesRoute = SeriesSeriesRouteImport.update({
  id: '/series/$series',
  path: '/series/$series',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlacesRoute,
} as any)
const FeedEventsDotrssRoute = FeedEventsDotrssRouteImport.update({
  id: '/feed/events.rss',
  path: '/feed/events.rss',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedArticlesDotrssRoute = FeedArticlesDotrssRouteImport.update({
  id: '/feed/articles.rss',
  path: '/feed/articles.rss',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSectionRoute = CSectionRouteImport.update({
  id: '/c/$section',
  path: '/c/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorRoute = AuthorsAuthorRouteImport.update({
  id: '/authors/$author',
  path: '/authors/$author',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaRoute = AreasAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => AreasRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedirectsRoute = AdminRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const TaxonomySlugRoute = TaxonomySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TaxonomyRoute,
} as any)
const CSectionSubRoute = CSectionSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => CSectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$taxonomy': typeof TaxonomyRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/advertise': typeof AdvertiseRoute
  '/areas': typeof AreasRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/newsletter': typeof NewsletterRoute
  '/listings': typeof ListingsRoute
  '/offers': typeof OffersRoute
  '/open-now': typeof OpenNowRoute
  '/places': typeof PlacesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/whats-on': typeof WhatsOnRoute
  '/$taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/areas/$area': typeof AreasAreaRoute
  '/authors/$author': typeof AuthorsAuthorRoute
  '/c/$section': typeof CSectionRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/feed/articles.rss': typeof FeedArticlesDotrssRoute
  '/feed/events.rss': typeof FeedEventsDotrssRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/series': typeof SeriesRoute
  '/series/$series': typeof SeriesSeriesRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/': typeof AdminIndexRoute
  '/c/$section/$sub': typeof CSectionSubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$taxonomy': typeof TaxonomyRouteWithChildren
  '/account': typeof AccountRoute
  '/contact': typeof ContactRoute
  '/advertise': typeof AdvertiseRoute
  '/areas': typeof AreasRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/newsletter': typeof NewsletterRoute
  '/listings': typeof ListingsRoute
  '/offers': typeof OffersRoute
  '/open-now': typeof OpenNowRoute
  '/places': typeof PlacesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/whats-on': typeof WhatsOnRoute
  '/$taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/areas/$area': typeof AreasAreaRoute
  '/authors/$author': typeof AuthorsAuthorRoute
  '/c/$section': typeof CSectionRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/feed/articles.rss': typeof FeedArticlesDotrssRoute
  '/feed/events.rss': typeof FeedEventsDotrssRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/series': typeof SeriesRoute
  '/series/$series': typeof SeriesSeriesRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin': typeof AdminIndexRoute
  '/c/$section/$sub': typeof CSectionSubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$taxonomy': typeof TaxonomyRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/advertise': typeof AdvertiseRoute
  '/areas': typeof AreasRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/newsletter': typeof NewsletterRoute
  '/listings': typeof ListingsRoute
  '/offers': typeof OffersRoute
  '/open-now': typeof OpenNowRoute
  '/places': typeof PlacesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/whats-on': typeof WhatsOnRoute
  '/$taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/areas/$area': typeof AreasAreaRoute
  '/authors/$author': typeof AuthorsAuthorRoute
  '/c/$section': typeof CSectionRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/feed/articles.rss': typeof FeedArticlesDotrssRoute
  '/feed/events.rss': typeof FeedEventsDotrssRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/series': typeof SeriesRoute
  '/series/$series': typeof SeriesSeriesRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/': typeof AdminIndexRoute
  '/c/$section/$sub': typeof CSectionSubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$taxonomy'
    | '/account'
    | '/admin'
    | '/advertise'
    | '/areas'
    | '/forgot-password'
    | '/listings'
    | '/offers'
    | '/open-now'
    | '/places'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/whats-on'
    | '/$taxonomy/$slug'
    | '/admin/ads'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/submissions'
    | '/admin/users'
    | '/areas/$area'
    | '/authors/$author'
    | '/c/$section'
    | '/events/$slug'
    | '/feed/articles.rss'
    | '/feed/events.rss'
    | '/places/$slug'
    | '/series/$series'
    | '/stories/$slug'
    | '/tag/$tag'
    | '/admin/'
    | '/c/$section/$sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$taxonomy'
    | '/account'
    | '/advertise'
    | '/areas'
    | '/forgot-password'
    | '/listings'
    | '/offers'
    | '/open-now'
    | '/places'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/whats-on'
    | '/$taxonomy/$slug'
    | '/admin/ads'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/submissions'
    | '/admin/users'
    | '/areas/$area'
    | '/authors/$author'
    | '/c/$section'
    | '/events/$slug'
    | '/feed/articles.rss'
    | '/feed/events.rss'
    | '/places/$slug'
    | '/series/$series'
    | '/stories/$slug'
    | '/tag/$tag'
    | '/admin'
    | '/c/$section/$sub'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$taxonomy'
    | '/account'
    | '/admin'
    | '/advertise'
    | '/areas'
    | '/forgot-password'
    | '/listings'
    | '/offers'
    | '/open-now'
    | '/places'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/whats-on'
    | '/$taxonomy/$slug'
    | '/admin/ads'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/offers'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/submissions'
    | '/admin/users'
    | '/areas/$area'
    | '/authors/$author'
    | '/c/$section'
    | '/events/$slug'
    | '/feed/articles.rss'
    | '/feed/events.rss'
    | '/places/$slug'
    | '/series/$series'
    | '/stories/$slug'
    | '/tag/$tag'
    | '/admin/'
    | '/c/$section/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  TaxonomyRoute: typeof TaxonomyRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  AreasRoute: typeof AreasRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ListingsRoute: typeof ListingsRoute
  OffersRoute: typeof OffersRoute
  OpenNowRoute: typeof OpenNowRoute
  PlacesRoute: typeof PlacesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  SubmitRoute: typeof SubmitRoute
  WhatsOnRoute: typeof WhatsOnRoute
  AuthorsAuthorRoute: typeof AuthorsAuthorRoute
  CSectionRoute: typeof CSectionRouteWithChildren
  EventsSlugRoute: typeof EventsSlugRoute
  FeedArticlesDotrssRoute: typeof FeedArticlesDotrssRoute
  FeedEventsDotrssRoute: typeof FeedEventsDotrssRoute
  SeriesSeriesRoute: typeof SeriesSeriesRoute
  TagTagRoute: typeof TagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-on': {
      id: '/whats-on'
      path: '/whats-on'
      fullPath: '/whats-on'
      preLoaderRoute: typeof WhatsOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-now': {
      id: '/open-now'
      path: '/open-now'
      fullPath: '/open-now'
      preLoaderRoute: typeof OpenNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$taxonomy': {
      id: '/$taxonomy'
      path: '/$taxonomy'
      fullPath: '/$taxonomy'
      preLoaderRoute: typeof TaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$series': {
      id: '/series/$series'
      path: '/series/$series'
      fullPath: '/series/$series'
      preLoaderRoute: typeof SeriesSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/feed/events.rss': {
      id: '/feed/events.rss'
      path: '/feed/events.rss'
      fullPath: '/feed/events.rss'
      preLoaderRoute: typeof FeedEventsDotrssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/articles.rss': {
      id: '/feed/articles.rss'
      path: '/feed/articles.rss'
      fullPath: '/feed/articles.rss'
      preLoaderRoute: typeof FeedArticlesDotrssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$section': {
      id: '/c/$section'
      path: '/c/$section'
      fullPath: '/c/$section'
      preLoaderRoute: typeof CSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$author': {
      id: '/authors/$author'
      path: '/authors/$author'
      fullPath: '/authors/$author'
      preLoaderRoute: typeof AuthorsAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$area': {
      id: '/areas/$area'
      path: '/$area'
      fullPath: '/areas/$area'
      preLoaderRoute: typeof AreasAreaRouteImport
      parentRoute: typeof AreasRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redirects': {
      id: '/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AdminRedirectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$taxonomy/$slug': {
      id: '/$taxonomy/$slug'
      path: '/$slug'
      fullPath: '/$taxonomy/$slug'
      preLoaderRoute: typeof TaxonomySlugRouteImport
      parentRoute: typeof TaxonomyRoute
    }
    '/c/$section/$sub': {
      id: '/c/$section/$sub'
      path: '/$sub'
      fullPath: '/c/$section/$sub'
      preLoaderRoute: typeof CSectionSubRouteImport
      parentRoute: typeof CSectionRoute
    }
  }
}

interface TaxonomyRouteChildren {
  TaxonomySlugRoute: typeof TaxonomySlugRoute
}

const TaxonomyRouteChildren: TaxonomyRouteChildren = {
  TaxonomySlugRoute: TaxonomySlugRoute,
}

const TaxonomyRouteWithChildren = TaxonomyRoute._addFileChildren(
  TaxonomyRouteChildren,
)

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminRedirectsRoute: typeof AdminRedirectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminRedirectsRoute: AdminRedirectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AreasRouteChildren {
  AreasAreaRoute: typeof AreasAreaRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasAreaRoute: AreasAreaRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

interface PlacesRouteChildren {
  PlacesSlugRoute: typeof PlacesSlugRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesSlugRoute: PlacesSlugRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface CSectionRouteChildren {
  CSectionSubRoute: typeof CSectionSubRoute
}

const CSectionRouteChildren: CSectionRouteChildren = {
  CSectionSubRoute: CSectionSubRoute,
}

const CSectionRouteWithChildren = CSectionRoute._addFileChildren(
  CSectionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  TaxonomyRoute: TaxonomyRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  AdvertiseRoute: AdvertiseRoute,
  AreasRoute: AreasRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NewsletterRoute: NewsletterRoute,
  ListingsRoute: ListingsRoute,
  OffersRoute: OffersRoute,
  OpenNowRoute: OpenNowRoute,
  PlacesRoute: PlacesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRouteWithChildren,
  SubmitRoute: SubmitRoute,
  WhatsOnRoute: WhatsOnRoute,
  AuthorsAuthorRoute: AuthorsAuthorRoute,
  CSectionRoute: CSectionRouteWithChildren,
  EventsSlugRoute: EventsSlugRoute,
  FeedArticlesDotrssRoute: FeedArticlesDotrssRoute,
  FeedEventsDotrssRoute: FeedEventsDotrssRoute,
  SeriesRoute: SeriesRoute,
  SeriesSeriesRoute: SeriesSeriesRoute,
  TagTagRoute: TagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
