/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsOnRouteImport } from './routes/whats-on'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as OpenNowRouteImport } from './routes/open-now'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as TaxonomyRouteImport } from './routes/$taxonomy'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TagTagRouteImport } from './routes/tag.$tag'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as SeriesSeriesRouteImport } from './routes/series.$series'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as FeedEventsDotrssRouteImport } from './routes/feed.events[.]rss'
import { Route as FeedArticlesDotrssRouteImport } from './routes/feed.articles[.]rss'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CSectionRouteImport } from './routes/c.$section'
import { Route as BusinessListingsRouteImport } from './routes/business.listings'
import { Route as AuthorsAuthorRouteImport } from './routes/authors.$author'
import { Route as AreasAreaRouteImport } from './routes/areas.$area'
import { Route as ApiImageProxyRouteImport } from './routes/api.image-proxy'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRedirectsRouteImport } from './routes/admin.redirects'
import { Route as AdminPwaRouteImport } from './routes/admin.pwa'
import { Route as AdminPollsRouteImport } from './routes/admin.polls'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEditorialPicksRouteImport } from './routes/admin.editorial-picks'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminAreasRouteImport } from './routes/admin.areas'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as TaxonomySlugRouteImport } from './routes/$taxonomy.$slug'
import { Route as CSectionSubRouteImport } from './routes/c.$section.$sub'
import { Route as ApiV1RedeemRouteImport } from './routes/api.v1.redeem'
import { Route as ApiV1OffersRouteImport } from './routes/api.v1.offers'
import { Route as ApiV1MeRouteImport } from './routes/api.v1.me'
import { Route as ApiV1ListingsRouteImport } from './routes/api.v1.listings'
import { Route as ApiV1GenerateCodeRouteImport } from './routes/api.v1.generate-code'
import { Route as ApiCronPublishRouteImport } from './routes/api.cron.publish'
import { Route as ApiV1OffersIdRouteImport } from './routes/api.v1.offers.$id'
import { Route as ApiV1MeRedemptionsRouteImport } from './routes/api.v1.me.redemptions'
import { Route as ApiV1MePushRouteImport } from './routes/api.v1.me.push'
import { Route as ApiV1MeListingRouteImport } from './routes/api.v1.me.listing'
import { Route as ApiV1MeFavouritesRouteImport } from './routes/api.v1.me.favourites'
import { Route as ApiV1ListingsIdRouteImport } from './routes/api.v1.listings.$id'
import { Route as ApiV1AuthRegisterRouteImport } from './routes/api.v1.auth.register'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api.v1.auth.login'
import { Route as ApiV1AuthForgotPasswordRouteImport } from './routes/api.v1.auth.forgot-password'

const WhatsOnRoute = WhatsOnRouteImport.update({
  id: '/whats-on',
  path: '/whats-on',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenNowRoute = OpenNowRouteImport.update({
  id: '/open-now',
  path: '/open-now',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxonomyRoute = TaxonomyRouteImport.update({
  id: '/$taxonomy',
  path: '/$taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TagTagRoute = TagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const SeriesSeriesRoute = SeriesSeriesRouteImport.update({
  id: '/$series',
  path: '/$series',
  getParentRoute: () => SeriesRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlacesRoute,
} as any)
const FeedEventsDotrssRoute = FeedEventsDotrssRouteImport.update({
  id: '/feed/events.rss',
  path: '/feed/events.rss',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedArticlesDotrssRoute = FeedArticlesDotrssRouteImport.update({
  id: '/feed/articles.rss',
  path: '/feed/articles.rss',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSectionRoute = CSectionRouteImport.update({
  id: '/c/$section',
  path: '/c/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessListingsRoute = BusinessListingsRouteImport.update({
  id: '/business/listings',
  path: '/business/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorRoute = AuthorsAuthorRouteImport.update({
  id: '/authors/$author',
  path: '/authors/$author',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasAreaRoute = AreasAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => AreasRoute,
} as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedirectsRoute = AdminRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPwaRoute = AdminPwaRouteImport.update({
  id: '/pwa',
  path: '/pwa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPollsRoute = AdminPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorialPicksRoute = AdminEditorialPicksRouteImport.update({
  id: '/editorial-picks',
  path: '/editorial-picks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAreasRoute = AdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const TaxonomySlugRoute = TaxonomySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TaxonomyRoute,
} as any)
const CSectionSubRoute = CSectionSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => CSectionRoute,
} as any)
const ApiV1RedeemRoute = ApiV1RedeemRouteImport.update({
  id: '/api/v1/redeem',
  path: '/api/v1/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OffersRoute = ApiV1OffersRouteImport.update({
  id: '/api/v1/offers',
  path: '/api/v1/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ListingsRoute = ApiV1ListingsRouteImport.update({
  id: '/api/v1/listings',
  path: '/api/v1/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenerateCodeRoute = ApiV1GenerateCodeRouteImport.update({
  id: '/api/v1/generate-code',
  path: '/api/v1/generate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPublishRoute = ApiCronPublishRouteImport.update({
  id: '/api/cron/publish',
  path: '/api/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OffersIdRoute = ApiV1OffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1OffersRoute,
} as any)
const ApiV1MeRedemptionsRoute = ApiV1MeRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => ApiV1MeRoute,
} as any)
const ApiV1MePushRoute = ApiV1MePushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => ApiV1MeRoute,
} as any)
const ApiV1MeListingRoute = ApiV1MeListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => ApiV1MeRoute,
} as any)
const ApiV1MeFavouritesRoute = ApiV1MeFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => ApiV1MeRoute,
} as any)
const ApiV1ListingsIdRoute = ApiV1ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ListingsRoute,
} as any)
const ApiV1AuthRegisterRoute = ApiV1AuthRegisterRouteImport.update({
  id: '/api/v1/auth/register',
  path: '/api/v1/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthForgotPasswordRoute = ApiV1AuthForgotPasswordRouteImport.update({
  id: '/api/v1/auth/forgot-password',
  path: '/api/v1/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$taxonomy': typeof TaxonomyRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/areas': typeof AreasRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/listings': typeof ListingsRoute
  '/newsletter': typeof NewsletterRoute
  '/offers': typeof OffersRoute
  '/open-now': typeof OpenNowRoute
  '/places': typeof PlacesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/whats-on': typeof WhatsOnRoute
  '/$taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/editorial-picks': typeof AdminEditorialPicksRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/pwa': typeof AdminPwaRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/areas/$area': typeof AreasAreaRoute
  '/authors/$author': typeof AuthorsAuthorRoute
  '/business/listings': typeof BusinessListingsRoute
  '/c/$section': typeof CSectionRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/feed/articles.rss': typeof FeedArticlesDotrssRoute
  '/feed/events.rss': typeof FeedEventsDotrssRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/series/$series': typeof SeriesSeriesRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/v1/generate-code': typeof ApiV1GenerateCodeRoute
  '/api/v1/listings': typeof ApiV1ListingsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRouteWithChildren
  '/api/v1/offers': typeof ApiV1OffersRouteWithChildren
  '/api/v1/redeem': typeof ApiV1RedeemRoute
  '/c/$section/$sub': typeof CSectionSubRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/listings/$id': typeof ApiV1ListingsIdRoute
  '/api/v1/me/favourites': typeof ApiV1MeFavouritesRoute
  '/api/v1/me/listing': typeof ApiV1MeListingRoute
  '/api/v1/me/push': typeof ApiV1MePushRoute
  '/api/v1/me/redemptions': typeof ApiV1MeRedemptionsRoute
  '/api/v1/offers/$id': typeof ApiV1OffersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$taxonomy': typeof TaxonomyRouteWithChildren
  '/account': typeof AccountRoute
  '/advertise': typeof AdvertiseRoute
  '/areas': typeof AreasRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/listings': typeof ListingsRoute
  '/newsletter': typeof NewsletterRoute
  '/offers': typeof OffersRoute
  '/open-now': typeof OpenNowRoute
  '/places': typeof PlacesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/whats-on': typeof WhatsOnRoute
  '/$taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/editorial-picks': typeof AdminEditorialPicksRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/pwa': typeof AdminPwaRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/areas/$area': typeof AreasAreaRoute
  '/authors/$author': typeof AuthorsAuthorRoute
  '/business/listings': typeof BusinessListingsRoute
  '/c/$section': typeof CSectionRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/feed/articles.rss': typeof FeedArticlesDotrssRoute
  '/feed/events.rss': typeof FeedEventsDotrssRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/series/$series': typeof SeriesSeriesRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin': typeof AdminIndexRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/v1/generate-code': typeof ApiV1GenerateCodeRoute
  '/api/v1/listings': typeof ApiV1ListingsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRouteWithChildren
  '/api/v1/offers': typeof ApiV1OffersRouteWithChildren
  '/api/v1/redeem': typeof ApiV1RedeemRoute
  '/c/$section/$sub': typeof CSectionSubRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/listings/$id': typeof ApiV1ListingsIdRoute
  '/api/v1/me/favourites': typeof ApiV1MeFavouritesRoute
  '/api/v1/me/listing': typeof ApiV1MeListingRoute
  '/api/v1/me/push': typeof ApiV1MePushRoute
  '/api/v1/me/redemptions': typeof ApiV1MeRedemptionsRoute
  '/api/v1/offers/$id': typeof ApiV1OffersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$taxonomy': typeof TaxonomyRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/areas': typeof AreasRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/listings': typeof ListingsRoute
  '/newsletter': typeof NewsletterRoute
  '/offers': typeof OffersRoute
  '/open-now': typeof OpenNowRoute
  '/places': typeof PlacesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRouteWithChildren
  '/submit': typeof SubmitRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/whats-on': typeof WhatsOnRoute
  '/$taxonomy/$slug': typeof TaxonomySlugRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/areas': typeof AdminAreasRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/editorial-picks': typeof AdminEditorialPicksRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/pwa': typeof AdminPwaRoute
  '/admin/redirects': typeof AdminRedirectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/areas/$area': typeof AreasAreaRoute
  '/authors/$author': typeof AuthorsAuthorRoute
  '/business/listings': typeof BusinessListingsRoute
  '/c/$section': typeof CSectionRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/feed/articles.rss': typeof FeedArticlesDotrssRoute
  '/feed/events.rss': typeof FeedEventsDotrssRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/series/$series': typeof SeriesSeriesRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/tag/$tag': typeof TagTagRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/v1/generate-code': typeof ApiV1GenerateCodeRoute
  '/api/v1/listings': typeof ApiV1ListingsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRouteWithChildren
  '/api/v1/offers': typeof ApiV1OffersRouteWithChildren
  '/api/v1/redeem': typeof ApiV1RedeemRoute
  '/c/$section/$sub': typeof CSectionSubRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/register': typeof ApiV1AuthRegisterRoute
  '/api/v1/listings/$id': typeof ApiV1ListingsIdRoute
  '/api/v1/me/favourites': typeof ApiV1MeFavouritesRoute
  '/api/v1/me/listing': typeof ApiV1MeListingRoute
  '/api/v1/me/push': typeof ApiV1MePushRoute
  '/api/v1/me/redemptions': typeof ApiV1MeRedemptionsRoute
  '/api/v1/offers/$id': typeof ApiV1OffersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$taxonomy'
    | '/account'
    | '/admin'
    | '/advertise'
    | '/areas'
    | '/contact'
    | '/forgot-password'
    | '/listings'
    | '/newsletter'
    | '/offers'
    | '/open-now'
    | '/places'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/series'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/unsubscribe'
    | '/whats-on'
    | '/$taxonomy/$slug'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/areas'
    | '/admin/articles'
    | '/admin/claims'
    | '/admin/comments'
    | '/admin/editorial-picks'
    | '/admin/events'
    | '/admin/import'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/offers'
    | '/admin/polls'
    | '/admin/pwa'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/subscribers'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/api/image-proxy'
    | '/areas/$area'
    | '/authors/$author'
    | '/business/listings'
    | '/c/$section'
    | '/collections/$slug'
    | '/events/$slug'
    | '/feed/articles.rss'
    | '/feed/events.rss'
    | '/places/$slug'
    | '/profile/$userId'
    | '/series/$series'
    | '/stories/$slug'
    | '/tag/$tag'
    | '/admin/'
    | '/api/cron/publish'
    | '/api/v1/generate-code'
    | '/api/v1/listings'
    | '/api/v1/me'
    | '/api/v1/offers'
    | '/api/v1/redeem'
    | '/c/$section/$sub'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/register'
    | '/api/v1/listings/$id'
    | '/api/v1/me/favourites'
    | '/api/v1/me/listing'
    | '/api/v1/me/push'
    | '/api/v1/me/redemptions'
    | '/api/v1/offers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$taxonomy'
    | '/account'
    | '/advertise'
    | '/areas'
    | '/contact'
    | '/forgot-password'
    | '/listings'
    | '/newsletter'
    | '/offers'
    | '/open-now'
    | '/places'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/series'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/unsubscribe'
    | '/whats-on'
    | '/$taxonomy/$slug'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/areas'
    | '/admin/articles'
    | '/admin/claims'
    | '/admin/comments'
    | '/admin/editorial-picks'
    | '/admin/events'
    | '/admin/import'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/offers'
    | '/admin/polls'
    | '/admin/pwa'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/subscribers'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/api/image-proxy'
    | '/areas/$area'
    | '/authors/$author'
    | '/business/listings'
    | '/c/$section'
    | '/collections/$slug'
    | '/events/$slug'
    | '/feed/articles.rss'
    | '/feed/events.rss'
    | '/places/$slug'
    | '/profile/$userId'
    | '/series/$series'
    | '/stories/$slug'
    | '/tag/$tag'
    | '/admin'
    | '/api/cron/publish'
    | '/api/v1/generate-code'
    | '/api/v1/listings'
    | '/api/v1/me'
    | '/api/v1/offers'
    | '/api/v1/redeem'
    | '/c/$section/$sub'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/register'
    | '/api/v1/listings/$id'
    | '/api/v1/me/favourites'
    | '/api/v1/me/listing'
    | '/api/v1/me/push'
    | '/api/v1/me/redemptions'
    | '/api/v1/offers/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$taxonomy'
    | '/account'
    | '/admin'
    | '/advertise'
    | '/areas'
    | '/contact'
    | '/forgot-password'
    | '/listings'
    | '/newsletter'
    | '/offers'
    | '/open-now'
    | '/places'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/series'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/stories'
    | '/submit'
    | '/unsubscribe'
    | '/whats-on'
    | '/$taxonomy/$slug'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/areas'
    | '/admin/articles'
    | '/admin/claims'
    | '/admin/comments'
    | '/admin/editorial-picks'
    | '/admin/events'
    | '/admin/import'
    | '/admin/listings'
    | '/admin/media'
    | '/admin/newsletter'
    | '/admin/offers'
    | '/admin/polls'
    | '/admin/pwa'
    | '/admin/redirects'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/subscribers'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/api/image-proxy'
    | '/areas/$area'
    | '/authors/$author'
    | '/business/listings'
    | '/c/$section'
    | '/collections/$slug'
    | '/events/$slug'
    | '/feed/articles.rss'
    | '/feed/events.rss'
    | '/places/$slug'
    | '/profile/$userId'
    | '/series/$series'
    | '/stories/$slug'
    | '/tag/$tag'
    | '/admin/'
    | '/api/cron/publish'
    | '/api/v1/generate-code'
    | '/api/v1/listings'
    | '/api/v1/me'
    | '/api/v1/offers'
    | '/api/v1/redeem'
    | '/c/$section/$sub'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/register'
    | '/api/v1/listings/$id'
    | '/api/v1/me/favourites'
    | '/api/v1/me/listing'
    | '/api/v1/me/push'
    | '/api/v1/me/redemptions'
    | '/api/v1/offers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  TaxonomyRoute: typeof TaxonomyRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  AreasRoute: typeof AreasRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ListingsRoute: typeof ListingsRoute
  NewsletterRoute: typeof NewsletterRoute
  OffersRoute: typeof OffersRoute
  OpenNowRoute: typeof OpenNowRoute
  PlacesRoute: typeof PlacesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  SubmitRoute: typeof SubmitRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhatsOnRoute: typeof WhatsOnRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  AuthorsAuthorRoute: typeof AuthorsAuthorRoute
  BusinessListingsRoute: typeof BusinessListingsRoute
  CSectionRoute: typeof CSectionRouteWithChildren
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  FeedArticlesDotrssRoute: typeof FeedArticlesDotrssRoute
  FeedEventsDotrssRoute: typeof FeedEventsDotrssRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  TagTagRoute: typeof TagTagRoute
  ApiCronPublishRoute: typeof ApiCronPublishRoute
  ApiV1GenerateCodeRoute: typeof ApiV1GenerateCodeRoute
  ApiV1ListingsRoute: typeof ApiV1ListingsRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRouteWithChildren
  ApiV1OffersRoute: typeof ApiV1OffersRouteWithChildren
  ApiV1RedeemRoute: typeof ApiV1RedeemRoute
  ApiV1AuthForgotPasswordRoute: typeof ApiV1AuthForgotPasswordRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthRegisterRoute: typeof ApiV1AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-on': {
      id: '/whats-on'
      path: '/whats-on'
      fullPath: '/whats-on'
      preLoaderRoute: typeof WhatsOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-now': {
      id: '/open-now'
      path: '/open-now'
      fullPath: '/open-now'
      preLoaderRoute: typeof OpenNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$taxonomy': {
      id: '/$taxonomy'
      path: '/$taxonomy'
      fullPath: '/$taxonomy'
      preLoaderRoute: typeof TaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tag/$tag': {
      id: '/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof TagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/series/$series': {
      id: '/series/$series'
      path: '/$series'
      fullPath: '/series/$series'
      preLoaderRoute: typeof SeriesSeriesRouteImport
      parentRoute: typeof SeriesRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/feed/events.rss': {
      id: '/feed/events.rss'
      path: '/feed/events.rss'
      fullPath: '/feed/events.rss'
      preLoaderRoute: typeof FeedEventsDotrssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/articles.rss': {
      id: '/feed/articles.rss'
      path: '/feed/articles.rss'
      fullPath: '/feed/articles.rss'
      preLoaderRoute: typeof FeedArticlesDotrssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$section': {
      id: '/c/$section'
      path: '/c/$section'
      fullPath: '/c/$section'
      preLoaderRoute: typeof CSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/listings': {
      id: '/business/listings'
      path: '/business/listings'
      fullPath: '/business/listings'
      preLoaderRoute: typeof BusinessListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$author': {
      id: '/authors/$author'
      path: '/authors/$author'
      fullPath: '/authors/$author'
      preLoaderRoute: typeof AuthorsAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$area': {
      id: '/areas/$area'
      path: '/$area'
      fullPath: '/areas/$area'
      preLoaderRoute: typeof AreasAreaRouteImport
      parentRoute: typeof AreasRoute
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redirects': {
      id: '/admin/redirects'
      path: '/redirects'
      fullPath: '/admin/redirects'
      preLoaderRoute: typeof AdminRedirectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pwa': {
      id: '/admin/pwa'
      path: '/pwa'
      fullPath: '/admin/pwa'
      preLoaderRoute: typeof AdminPwaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/polls': {
      id: '/admin/polls'
      path: '/polls'
      fullPath: '/admin/polls'
      preLoaderRoute: typeof AdminPollsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editorial-picks': {
      id: '/admin/editorial-picks'
      path: '/editorial-picks'
      fullPath: '/admin/editorial-picks'
      preLoaderRoute: typeof AdminEditorialPicksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/areas': {
      id: '/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AdminAreasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$taxonomy/$slug': {
      id: '/$taxonomy/$slug'
      path: '/$slug'
      fullPath: '/$taxonomy/$slug'
      preLoaderRoute: typeof TaxonomySlugRouteImport
      parentRoute: typeof TaxonomyRoute
    }
    '/c/$section/$sub': {
      id: '/c/$section/$sub'
      path: '/$sub'
      fullPath: '/c/$section/$sub'
      preLoaderRoute: typeof CSectionSubRouteImport
      parentRoute: typeof CSectionRoute
    }
    '/api/v1/redeem': {
      id: '/api/v1/redeem'
      path: '/api/v1/redeem'
      fullPath: '/api/v1/redeem'
      preLoaderRoute: typeof ApiV1RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/offers': {
      id: '/api/v1/offers'
      path: '/api/v1/offers'
      fullPath: '/api/v1/offers'
      preLoaderRoute: typeof ApiV1OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/listings': {
      id: '/api/v1/listings'
      path: '/api/v1/listings'
      fullPath: '/api/v1/listings'
      preLoaderRoute: typeof ApiV1ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/generate-code': {
      id: '/api/v1/generate-code'
      path: '/api/v1/generate-code'
      fullPath: '/api/v1/generate-code'
      preLoaderRoute: typeof ApiV1GenerateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish': {
      id: '/api/cron/publish'
      path: '/api/cron/publish'
      fullPath: '/api/cron/publish'
      preLoaderRoute: typeof ApiCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/offers/$id': {
      id: '/api/v1/offers/$id'
      path: '/$id'
      fullPath: '/api/v1/offers/$id'
      preLoaderRoute: typeof ApiV1OffersIdRouteImport
      parentRoute: typeof ApiV1OffersRoute
    }
    '/api/v1/me/redemptions': {
      id: '/api/v1/me/redemptions'
      path: '/redemptions'
      fullPath: '/api/v1/me/redemptions'
      preLoaderRoute: typeof ApiV1MeRedemptionsRouteImport
      parentRoute: typeof ApiV1MeRoute
    }
    '/api/v1/me/push': {
      id: '/api/v1/me/push'
      path: '/push'
      fullPath: '/api/v1/me/push'
      preLoaderRoute: typeof ApiV1MePushRouteImport
      parentRoute: typeof ApiV1MeRoute
    }
    '/api/v1/me/listing': {
      id: '/api/v1/me/listing'
      path: '/listing'
      fullPath: '/api/v1/me/listing'
      preLoaderRoute: typeof ApiV1MeListingRouteImport
      parentRoute: typeof ApiV1MeRoute
    }
    '/api/v1/me/favourites': {
      id: '/api/v1/me/favourites'
      path: '/favourites'
      fullPath: '/api/v1/me/favourites'
      preLoaderRoute: typeof ApiV1MeFavouritesRouteImport
      parentRoute: typeof ApiV1MeRoute
    }
    '/api/v1/listings/$id': {
      id: '/api/v1/listings/$id'
      path: '/$id'
      fullPath: '/api/v1/listings/$id'
      preLoaderRoute: typeof ApiV1ListingsIdRouteImport
      parentRoute: typeof ApiV1ListingsRoute
    }
    '/api/v1/auth/register': {
      id: '/api/v1/auth/register'
      path: '/api/v1/auth/register'
      fullPath: '/api/v1/auth/register'
      preLoaderRoute: typeof ApiV1AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/forgot-password': {
      id: '/api/v1/auth/forgot-password'
      path: '/api/v1/auth/forgot-password'
      fullPath: '/api/v1/auth/forgot-password'
      preLoaderRoute: typeof ApiV1AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TaxonomyRouteChildren {
  TaxonomySlugRoute: typeof TaxonomySlugRoute
}

const TaxonomyRouteChildren: TaxonomyRouteChildren = {
  TaxonomySlugRoute: TaxonomySlugRoute,
}

const TaxonomyRouteWithChildren = TaxonomyRoute._addFileChildren(
  TaxonomyRouteChildren,
)

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAreasRoute: typeof AdminAreasRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminEditorialPicksRoute: typeof AdminEditorialPicksRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPollsRoute: typeof AdminPollsRoute
  AdminPwaRoute: typeof AdminPwaRoute
  AdminRedirectsRoute: typeof AdminRedirectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAreasRoute: AdminAreasRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminEditorialPicksRoute: AdminEditorialPicksRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminImportRoute: AdminImportRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPollsRoute: AdminPollsRoute,
  AdminPwaRoute: AdminPwaRoute,
  AdminRedirectsRoute: AdminRedirectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AreasRouteChildren {
  AreasAreaRoute: typeof AreasAreaRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasAreaRoute: AreasAreaRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

interface PlacesRouteChildren {
  PlacesSlugRoute: typeof PlacesSlugRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesSlugRoute: PlacesSlugRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

interface SeriesRouteChildren {
  SeriesSeriesRoute: typeof SeriesSeriesRoute
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSeriesRoute: SeriesSeriesRoute,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

interface CSectionRouteChildren {
  CSectionSubRoute: typeof CSectionSubRoute
}

const CSectionRouteChildren: CSectionRouteChildren = {
  CSectionSubRoute: CSectionSubRoute,
}

const CSectionRouteWithChildren = CSectionRoute._addFileChildren(
  CSectionRouteChildren,
)

interface ApiV1ListingsRouteChildren {
  ApiV1ListingsIdRoute: typeof ApiV1ListingsIdRoute
}

const ApiV1ListingsRouteChildren: ApiV1ListingsRouteChildren = {
  ApiV1ListingsIdRoute: ApiV1ListingsIdRoute,
}

const ApiV1ListingsRouteWithChildren = ApiV1ListingsRoute._addFileChildren(
  ApiV1ListingsRouteChildren,
)

interface ApiV1MeRouteChildren {
  ApiV1MeFavouritesRoute: typeof ApiV1MeFavouritesRoute
  ApiV1MeListingRoute: typeof ApiV1MeListingRoute
  ApiV1MePushRoute: typeof ApiV1MePushRoute
  ApiV1MeRedemptionsRoute: typeof ApiV1MeRedemptionsRoute
}

const ApiV1MeRouteChildren: ApiV1MeRouteChildren = {
  ApiV1MeFavouritesRoute: ApiV1MeFavouritesRoute,
  ApiV1MeListingRoute: ApiV1MeListingRoute,
  ApiV1MePushRoute: ApiV1MePushRoute,
  ApiV1MeRedemptionsRoute: ApiV1MeRedemptionsRoute,
}

const ApiV1MeRouteWithChildren =
  ApiV1MeRoute._addFileChildren(ApiV1MeRouteChildren)

interface ApiV1OffersRouteChildren {
  ApiV1OffersIdRoute: typeof ApiV1OffersIdRoute
}

const ApiV1OffersRouteChildren: ApiV1OffersRouteChildren = {
  ApiV1OffersIdRoute: ApiV1OffersIdRoute,
}

const ApiV1OffersRouteWithChildren = ApiV1OffersRoute._addFileChildren(
  ApiV1OffersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  TaxonomyRoute: TaxonomyRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  AreasRoute: AreasRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ListingsRoute: ListingsRoute,
  NewsletterRoute: NewsletterRoute,
  OffersRoute: OffersRoute,
  OpenNowRoute: OpenNowRoute,
  PlacesRoute: PlacesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRouteWithChildren,
  SubmitRoute: SubmitRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhatsOnRoute: WhatsOnRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  AuthorsAuthorRoute: AuthorsAuthorRoute,
  BusinessListingsRoute: BusinessListingsRoute,
  CSectionRoute: CSectionRouteWithChildren,
  CollectionsSlugRoute: CollectionsSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  FeedArticlesDotrssRoute: FeedArticlesDotrssRoute,
  FeedEventsDotrssRoute: FeedEventsDotrssRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  TagTagRoute: TagTagRoute,
  ApiCronPublishRoute: ApiCronPublishRoute,
  ApiV1GenerateCodeRoute: ApiV1GenerateCodeRoute,
  ApiV1ListingsRoute: ApiV1ListingsRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRouteWithChildren,
  ApiV1OffersRoute: ApiV1OffersRouteWithChildren,
  ApiV1RedeemRoute: ApiV1RedeemRoute,
  ApiV1AuthForgotPasswordRoute: ApiV1AuthForgotPasswordRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthRegisterRoute: ApiV1AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
